### ISSUE TITLE
some levels unplayable

### ISSUE THREAD

**Issue by treirouxel88** [vittorioromeo/SSVOpenHexagon#373]
![image](https://user-images.githubusercontent.com/83276347/178033442-4a489381-61ca-4687-939c-51b52b7db31f.png)
I can't play some levels due to a nil value error (apparently)

**Comment by vittorioromeo** [comment]
Is this on the latest Steam version, on Windows?

**Comment by treirouxel88** [comment]
yup, fixed by running an integrity check.
