### ISSUE TITLE
Can't launch on Arch Linux

### ISSUE THREAD

**Issue by djalexkidd** [vittorioromeo/SSVOpenHexagon#384]
Hello,
The game segfaults when I launch it on Arch Linux (both on Xorg and Wayland).
I used the AUR version (open-hexagon-git).

```
[Steam]                               Initializing Steam API
[S_API] SteamAPI_Init(): Loaded '/home/user/.local/share/Steam/linux64/steamclient.so' OK.
[S_API FAIL] SteamAPI_Init() failed; connect to global user failed.
[Steam]                               Failed to initialize Steam API
[Discord]                             Successfully initialized core
[Discord]                             Successfully registered command
[Discord]                             Successfully registered Steam app
[::loadConfig]                        loading config
[hg::Config::root()]                  User-defined `config.json` file found
[::reapplyResolution]                 reapplying resolution
[1]    8162 segmentation fault (core dumped)  ./SSVOpenHexagon
```

**Comment by Bauumm** [comment]
This is a known issue. Run it with `LD_PRELOAD=libstdc++.so.6` to fix

**Comment by djalexkidd** [comment]
Thank you it worked !

**Comment by vittorioromeo** [comment]
> This is a known issue. Run it with `LD_PRELOAD=libstdc++.so.6` to fix

Would adding that to https://github.com/vittorioromeo/SSVOpenHexagon/blob/master/_RELEASE/run_ssvopenhexagon_linux.sh solve the issue?

**Comment by Bauumm** [comment]
I remember it not working on some distros that had libstdc++.so.6 in another location (ubuntu if i remember correctly). Just not bundling the lib with the game seems to have fixed it for most people so far.
But what almost all packaged software for Linux does normally is just compiling on a old version of glibc so it works everywhere.
